import java.util.HashMap;

import org.dom4j.DocumentException;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;

import com.justep.olap.common.WEBConstants;
import com.justep.system.data.SQL;
import com.justep.system.data.Table;

public class OfficePerformanceReport {
	public static Table countTaskReport(String beginDate,String endDate,String orgID) throws DocumentException{
		String webAbsPath = WEBConstants.getWebRootAbsPath();
		String configPath = webAbsPath.substring(0, webAbsPath.indexOf("apache-tomcat")) + "apache-tomcat\\conf\\server.xml";
		SAXReader xmlReader = new SAXReader();
		Node ndORCL = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@username");
		String dbNameORCL = ndORCL.getStringValue();
		Node ndMS = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@url");
		String dbNameMS = ndMS.getStringValue().substring(ndMS.getStringValue().lastIndexOf("/")+1, ndMS.getStringValue().length());
		String dbNameMySQL = dbNameMS;
		
		String orclSql = "",msSql = "",mySql="",orgCondition="",dateConditionOrcl="",dateConditionMS="",dateConditionMySQL="";
		if((!beginDate.equals("") || !beginDate.equals(null)) && (endDate.equals("") || endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME >= TO_DATE('" + beginDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME >= CAST('" + beginDate + "' AS DATETIME)) ";
			dateConditionMySQL = " AND (TASK.SCREATETIME >= str_to_date('" + beginDate + "' ,'%Y-%m-%d')) ";
		}else if((!beginDate.equals("") || !beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND ((TASK.SCREATETIME >= TO_DATE('" + beginDate
			+ "','YYYY-MM-DD') AND TASK.SCREATETIME < TO_DATE('" + endDate
			+ "','YYYY-MM-DD'))) ";
			dateConditionMS = " AND ((TASK.SCREATETIME >= CAST('" + beginDate
			+ "' AS DATETIME) AND TASK.SCREATETIME < CAST('" + endDate
			+ "' AS DATETIME))) ";
			dateConditionMySQL = " AND ((TASK.SCREATETIME >= str_to_date('" + beginDate
			+ "' ,'%Y-%m-%d') AND TASK.SCREATETIME < str_to_date('" + endDate
			+ "' ,'%Y-%m-%d'))) ";
		}else if((beginDate.equals("") || beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME < TO_DATE('" + endDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME < CAST('" + endDate + "' AS DATETIME)) ";
			dateConditionMySQL = " AND (TASK.SCREATETIME < str_to_date('" + endDate + "' ,'%Y-%m-%d')) ";
		}
		if(orgID.equals("") || orgID.equals(null)){
			orgCondition = " AND (OPORG.SPARENT is null) ";
		}else{
			orgCondition = " AND (OPORG.SID = '" + orgID + "') ";
		}
		
		orclSql = "SELECT ATALL.ORGID,(ATALL.ORGNAME) AS ORGNAME,(ATALL.ATALLNUM) AS COUNTTASK,(ATALL.PRO) AS PROCESS,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HA,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24N,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24A,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48A,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DA,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AA"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID <> 'tesAborted' OR TASK.SSTATUSID <> 'tesCanceled')";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += "GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 8";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT8 ON AT8.ORGID =ATALL.ORGID AND AT8.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 8 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 24)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT24 ON AT24.ORGID =ATALL.ORGID AND AT24.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 24 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 48)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT48 ON AT48.ORGID =ATALL.ORGID AND AT48.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 48 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 148)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT7 ON AT7.ORGID =ATALL.ORGID AND AT7.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 148 ";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT7A ON AT7A.ORGID =ATALL.ORGID AND AT7A.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID <> 'tesAborted' OR TASK.SSTATUSID <> 'tesCanceled')";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) PROALL ON PROALL.ORGID=ATALL.ORGID AND PROALL.PRO =ATALL.PRO";
		
		msSql = "SELECT ATALL.ORGID, (ATALL.ORGNAME)AS ORGNAME, (ATALL.ATALLNUM)AS COUNTTASK,(ATALL.PRO) AS PROCESS,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM / ATALL.ATALLNUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK8HA,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK24N,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM / ATALL.ATALLNUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK24A,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK48N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM / ATALL.ATALLNUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK48A,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM   AS DECIMAL(15, 4)) END)AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM / ATALL.ATALLNUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK7DA,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM   AS DECIMAL(15, 4)) END)AS TIMELYTASK7AN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM / ATALL.ATALLNUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK7AA"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID != 'TESABORTED' OR TASK.SSTATUSID != 'TESCANCELED')";
		
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 8";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS AT8 ON AT8.ORGID =ATALL.ORGID AND AT8.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 8 AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 24)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS AT24 ON AT24.ORGID =ATALL.ORGID AND AT24.PRO =ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 24 AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 48)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS AT48 ON AT48.ORGID =ATALL.ORGID AND AT48.PRO =ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 48 AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 148)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += "GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS AT7 ON AT7.ORGID =ATALL.ORGID AND AT7.PRO =ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 148 ";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += "GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS AT7A ON AT7A.ORGID =ATALL.ORGID AND AT7A.PRO =ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID != 'TESABORTED' OR TASK.SSTATUSID != 'TESCANCELED')";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AS PROALL ON PROALL.ORGID=ATALL.ORGID AND PROALL.PRO = ATALL.PRO";
		
		
		mySql = "SELECT ATALL.ORGID,(ATALL.ORGNAME) AS ORGNAME,(ATALL.ATALLNUM) AS COUNTTASK,(ATALL.PRO) AS PROCESS,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HA,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24N,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24A,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48A,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DA,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM / ATALL.ATALLNUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AA"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID <> 'tesAborted' OR TASK.SSTATUSID <> 'tesCanceled')";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += "GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 8";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT8 ON AT8.ORGID =ATALL.ORGID AND AT8.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 8 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 24)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT24 ON AT24.ORGID =ATALL.ORGID AND AT24.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID ,'%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 24 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 48)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT48 ON AT48.ORGID =ATALL.ORGID AND AT48.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 48 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 148)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT7 ON AT7.ORGID =ATALL.ORGID AND AT7.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 148 ";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) AT7A ON AT7A.ORGID =ATALL.ORGID AND AT7A.PRO=ATALL.PRO"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,TASK.SPROCESS AS PRO,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID <> 'tesAborted' OR TASK.SSTATUSID <> 'tesCanceled')";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME,TASK.SPROCESS) PROALL ON PROALL.ORGID=ATALL.ORGID AND PROALL.PRO =ATALL.PRO";
		
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put("ORACLE",orclSql);
		sqlMap.put("MSSQL",msSql);
		sqlMap.put("MYSQL",mySql);
		
		return SQL.select(sqlMap,null,"/OA/officePerformance/data");
	}

	public static Table countTaskPieReport(String beginDate,String endDate,String orgID) throws DocumentException{
		String webAbsPath = WEBConstants.getWebRootAbsPath();
		String configPath = webAbsPath.substring(0, webAbsPath.indexOf("apache-tomcat")) + "apache-tomcat\\conf\\server.xml";
		SAXReader xmlReader = new SAXReader();
		Node ndORCL = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@username");
		String dbNameORCL = ndORCL.getStringValue();
		Node ndMS = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@url");
		String dbNameMS = ndMS.getStringValue().substring(ndMS.getStringValue().lastIndexOf("/")+1, ndMS.getStringValue().length());
		String dbNameMySQL = dbNameMS;
		
		String orclSql = "",msSql = "",mySql="",orgCondition="",dateConditionOrcl="",dateConditionMS="",dateConditionMySQL="";
		
		if((!beginDate.equals("") || !beginDate.equals(null)) && (endDate.equals("") || endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME >= TO_DATE('" + beginDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME >= CAST('" + beginDate + "' AS DATETIME)) ";
			dateConditionMySQL = " AND (TASK.SCREATETIME >= str_to_date('" + beginDate + "','%Y-%m-%d')) ";
		}else if((!beginDate.equals("") || !beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND ((TASK.SCREATETIME >= TO_DATE('" + beginDate
			+ "','YYYY-MM-DD') AND TASK.SCREATETIME < TO_DATE('" + endDate
			+ "','YYYY-MM-DD'))) ";
			dateConditionMS = " AND ((TASK.SCREATETIME >= CAST('" + beginDate
			+ "' AS DATETIME) AND TASK.SCREATETIME < CAST('" + endDate
			+ "' AS DATETIME))) ";
			dateConditionMySQL = " AND ((TASK.SCREATETIME >= str_to_date('" + beginDate
			+ "' ,'%Y-%m-%d') AND TASK.SCREATETIME < str_to_date('" + endDate
			+ "' ,'%Y-%m-%d'))) ";
		}else if((beginDate.equals("") || beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME < TO_DATE('" + endDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME < CAST('" + endDate + "' AS DATETIME)) ";
			dateConditionMySQL = " AND (TASK.SCREATETIME < str_to_date('" + endDate + "' ,'%Y-%m-%d')) ";
		}
		
		if(orgID.equals("") || orgID.equals(null)){
			orgCondition = " ON (OPORG.SPARENT is null) ";
		}else{
			orgCondition = " ON (OPORG.SID = '" + orgID + "') ";
		}
		
		orclSql = "SELECT (OPORG.SID) AS ORGID,(OPORG.SNAME) AS ORGNAME,COUNT(ATALL.SID) AS ATALLNUM, (OPORG.SNAME||':'||CONFIG.FMNAME) AS ATALLXY"
			+ " FROM " + dbNameORCL +".RT_CONFIG CONFIG JOIN " + dbNameORCL +".SA_OPORG OPORG";
		orclSql += orgCondition;
		orclSql += " LEFT JOIN (SELECT TASK.SID AS SID,TASK.SSTATUSID AS SSTATUSID,TASK.SEXPECTSTARTTIME AS SESTARTTIME,TASK.SEXPECTFINISHTIME AS SEFINISHTIME,TASK.SEXECUTORFID"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND TASK.SSTATUSID <> 'tesAborted'";
		orclSql += dateConditionOrcl;
		orclSql += ") ATALL ON (ATALL.SSTATUSID = 'tesFinished' OR ATALL.SSTATUSID = 'tesReturned' OR ATALL.SSTATUSID = 'tesTransmited') AND ((ATALL.SEFINISHTIME - ATALL.SESTARTTIME) * 24 >= CONFIG.FMIN AND (ATALL.SEFINISHTIME - ATALL.SESTARTTIME) * 24 < CONFIG.FMAX) AND ATALL.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " GROUP BY CONFIG.FMIN, CONFIG.FMAX, OPORG.SID, OPORG.SNAME, CONFIG.FMNAME";
		
		msSql = "SELECT (OPORG.SID) AS ORGID,(OPORG.SNAME) AS ORGNAME,COUNT(ATALL.SID) AS ATALLNUM, (OPORG.SNAME + ':' + CONFIG.FMNAME) AS ATALLXY"
			+ " FROM "+ dbNameMS +".RT_CONFIG AS CONFIG JOIN "+ dbNameMS +".SA_OPORG OPORG ";
		msSql += orgCondition;
		msSql += " LEFT JOIN (SELECT TASK.SID AS SID,TASK.SSTATUSID AS SSTATUSID,TASK.SEXPECTSTARTTIME AS SESTARTTIME,TASK.SEXPECTFINISHTIME AS SEFINISHTIME,TASK.SEXECUTORFID"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND TASK.SSTATUSID != 'TESABORTED'";
		msSql += dateConditionMS;
		msSql += ") AS ATALL ON (ATALL.SSTATUSID = 'TESFINISHED' OR ATALL.SSTATUSID = 'TESRETURNED' OR ATALL.SSTATUSID = 'TESTRANSMITED') AND(DATEDIFF(HOUR,ATALL.SESTARTTIME,ATALL.SEFINISHTIME) >=CONFIG.FMIN AND DATEDIFF(HOUR,ATALL.SESTARTTIME,ATALL.SEFINISHTIME) <CONFIG.FMAX) AND ATALL.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " GROUP BY CONFIG.FMIN, CONFIG.FMAX,OPORG.SID, OPORG.SNAME,CONFIG.FMNAME";
		
		
		mySql = "SELECT (OPORG.SID) AS ORGID,(OPORG.SNAME) AS ORGNAME,COUNT(ATALL.SID) AS ATALLNUM, (concat(OPORG.SNAME , ':' , CONFIG.FMNAME)) AS ATALLXY"
			+ " FROM " + dbNameMySQL +".RT_CONFIG CONFIG JOIN " + dbNameMySQL +".SA_OPORG OPORG";
		mySql += orgCondition;
		mySql += " LEFT JOIN (SELECT TASK.SID AS SID,TASK.SSTATUSID AS SSTATUSID,TASK.SEXPECTSTARTTIME AS SESTARTTIME,TASK.SEXPECTFINISHTIME AS SEFINISHTIME,TASK.SEXECUTORFID"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND TASK.SSTATUSID <> 'tesAborted'";
		mySql += dateConditionMySQL;
		mySql += ") ATALL ON (ATALL.SSTATUSID = 'tesFinished' OR ATALL.SSTATUSID = 'tesReturned' OR ATALL.SSTATUSID = 'tesTransmited') AND ((ATALL.SEFINISHTIME - ATALL.SESTARTTIME) * 24 >= CONFIG.FMIN AND (ATALL.SEFINISHTIME - ATALL.SESTARTTIME) * 24 < CONFIG.FMAX) AND ATALL.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " GROUP BY CONFIG.FMIN, CONFIG.FMAX, OPORG.SID, OPORG.SNAME, CONFIG.FMNAME";

		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put("ORACLE",orclSql);
		sqlMap.put("MSSQL",msSql);
		sqlMap.put("MYSQL",mySql);
		
		return SQL.select(sqlMap,null,"/OA/officePerformance/data");
	}
	public static Table countTaskSeriesReport(String beginDate,String endDate,String orgID) throws DocumentException{
		String webAbsPath = WEBConstants.getWebRootAbsPath();
		String configPath = webAbsPath.substring(0, webAbsPath.indexOf("apache-tomcat")) + "apache-tomcat\\conf\\server.xml";
		SAXReader xmlReader = new SAXReader();
		Node ndORCL = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@username");
		String dbNameORCL = ndORCL.getStringValue();
		Node ndMS = xmlReader.read(configPath).getRootElement().selectSingleNode("//Resource[@name='system']/@url");
		String dbNameMS = ndMS.getStringValue().substring(ndMS.getStringValue().lastIndexOf("/")+1, ndMS.getStringValue().length());
		String dbNameMySQL = dbNameMS;
		
		String orclSql = "",msSql = "",mySql="",orgCondition="",dateConditionOrcl="",dateConditionMS="",dateConditionMySQL="";
		
		if((!beginDate.equals("") || !beginDate.equals(null)) && (endDate.equals("") || endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME >= TO_DATE('" + beginDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME >= CAST('" + beginDate + "' AS DATETIME)) ";
			dateConditionMS = " AND (TASK.SCREATETIME >= str_to_date('" + beginDate + "' ,'%Y-%m-%d')) ";
		}else if((!beginDate.equals("") || !beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND ((TASK.SCREATETIME >= TO_DATE('" + beginDate
			+ "','YYYY-MM-DD') AND TASK.SCREATETIME < TO_DATE('" + endDate
			+ "','YYYY-MM-DD'))) ";
			dateConditionMS = " AND ((TASK.SCREATETIME >= CAST('" + beginDate
			+ "' AS DATETIME) AND TASK.SCREATETIME < CAST('" + endDate
			+ "' AS DATETIME))) ";
			dateConditionMS = " AND ((TASK.SCREATETIME >= str_to_date('" + beginDate
			+ "' ,'%Y-%m-%d') AND TASK.SCREATETIME < str_to_date('" + endDate
			+ "' ,'%Y-%m-%d'))) ";
		}else if((beginDate.equals("") || beginDate.equals(null)) && (!endDate.equals("") || !endDate.equals(null))){
			dateConditionOrcl = " AND (TASK.SCREATETIME < TO_DATE('" + endDate + "','YYYY-MM-DD')) ";
			dateConditionMS = " AND (TASK.SCREATETIME < CAST('" + endDate + "' AS DATETIME)) ";
			dateConditionMS = " AND (TASK.SCREATETIME < str_to_date('" + endDate + "' ,'%Y-%m-%d')) ";
		}
		
		if(orgID.equals("") || orgID.equals(null)){
			orgCondition = " AND (OPORG.SPARENT is null) ";
		}else{
			orgCondition = " AND (OPORG.SID = '" + orgID + "') ";
		}
		
		orclSql = "SELECT ATALL.ORGID,(ATALL.ORGNAME) AS ORGNAME,(ATALL.ATALLNUM) AS COUNTTASK,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48N,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AN"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND TASK.SSTATUSID <> 'tesAborted'";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME) ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND  (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 8";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql +=" GROUP BY OPORG.SID, OPORG.SNAME) AT8 ON AT8.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 8 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 24)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME) AT24 ON AT24.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 24 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 48)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME) AT48 ON AT48.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 48 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 148)";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME) AT7 ON AT7.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM " + dbNameORCL +".SA_TASK TASK"
			+ " JOIN " + dbNameORCL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID || '%'"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 148 ";
		orclSql += orgCondition;
		orclSql += dateConditionOrcl;
		orclSql += " GROUP BY OPORG.SID, OPORG.SNAME) AT7A ON AT7A.ORGID =ATALL.ORGID";
		
		msSql = "SELECT ATALL.ORGID, (ATALL.ORGNAME)AS ORGNAME, (ATALL.ATALLNUM)AS COUNTTASK,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK24N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM  AS DECIMAL(15, 4)) END)AS TIMELYTASK48N,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM   AS DECIMAL(15, 4)) END)AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM   AS DECIMAL(15, 4)) END)AS TIMELYTASK7AN"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND TASK.SSTATUSID != 'TESABORTED'";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME) AS ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND  DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 8";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME) AS AT8 ON AT8.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 8  AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 24)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME) AS AT24 ON AT24.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 24  AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 48)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME) AS AT48 ON AT48.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 48  AND DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) < 148)";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql +=" GROUP BY OPORG.SID, OPORG.SNAME) AS AT7 ON AT7.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM "+ dbNameMS +".SA_TASK AS TASK"
			+ " JOIN "+ dbNameMS +".SA_OPORG AS OPORG ON TASK.SEXECUTORFID LIKE OPORG.SFID + '%'"
			+ " WHERE TASK.SKINDID != 'TKPROCESSINSTANCE' AND (TASK.SSTATUSID = 'TESFINISHED' OR TASK.SSTATUSID = 'TESRETURNED' OR TASK.SSTATUSID = 'TESTRANSMITED') AND (DATEDIFF(HOUR, TASK.SEXPECTSTARTTIME, TASK.SEXPECTFINISHTIME) >= 148 )";
		msSql += orgCondition;
		msSql += dateConditionMS;
		msSql += " GROUP BY OPORG.SID, OPORG.SNAME) AS AT7A ON AT7A.ORGID =ATALL.ORGID";
		

		mySql = "SELECT ATALL.ORGID,(ATALL.ORGNAME) AS ORGNAME,(ATALL.ATALLNUM) AS COUNTTASK,"
			+ "(CASE WHEN AT8.AT8NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT8.AT8NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK8HN,"
			+ "(CASE WHEN AT24.AT24NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT24.AT24NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK24N,"
			+ "(CASE WHEN AT48.AT48NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT48.AT48NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK48N,"
			+ "(CASE WHEN AT7.AT7NUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7.AT7NUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7DN,"
			+ "(CASE WHEN AT7A.AT7ANUM IS NULL OR ATALL.ATALLNUM = 0 THEN 0 ELSE CAST(AT7A.AT7ANUM AS DECIMAL(15, 4)) END) AS TIMELYTASK7AN"
			+ " FROM (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,COUNT(TASK.SID) AS ATALLNUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND TASK.SSTATUSID <> 'tesAborted'";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME) ATALL"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT8NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND  (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 8";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql +=" GROUP BY OPORG.SID, OPORG.SNAME) AT8 ON AT8.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT24NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 8 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 24)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME) AT24 ON AT24.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT48NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 24 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 48)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME) AT48 ON AT48.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7NUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND ((TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 48 AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 < 148)";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME) AT7 ON AT7.ORGID =ATALL.ORGID"
			+ " LEFT JOIN (SELECT OPORG.SID AS ORGID,OPORG.SNAME AS ORGNAME,CAST(COUNT(TASK.SID) AS DECIMAL) AS AT7ANUM"
			+ " FROM " + dbNameMySQL +".SA_TASK TASK"
			+ " JOIN " + dbNameMySQL +".SA_OPORG OPORG ON TASK.SEXECUTORFID LIKE concat(OPORG.SFID , '%')"
			+ " WHERE TASK.SKINDID <> 'tkProcessInstance' AND (TASK.SSTATUSID = 'tesFinished' OR TASK.SSTATUSID = 'tesReturned' OR TASK.SSTATUSID = 'tesTransmited') AND (TASK.SEXPECTFINISHTIME - TASK.SEXPECTSTARTTIME)*24 >= 148 ";
		mySql += orgCondition;
		mySql += dateConditionMySQL;
		mySql += " GROUP BY OPORG.SID, OPORG.SNAME) AT7A ON AT7A.ORGID =ATALL.ORGID";
		
		HashMap<String,String> sqlMap = new HashMap<String,String>();
		sqlMap.put("ORACLE",orclSql);
		sqlMap.put("MSSQL",msSql);
		sqlMap.put("MYSQL",mySql);
		
		return SQL.select(sqlMap,null,"/OA/officePerformance/data");
	}
}